#!/bin/bash
# $Id: perdevice,v 1.4 2009-08-05 06:18:30 nick Exp $

PROGRAM=$1
BAUDRATE=${2:-9600}

(
	for DEVICE in /dev/radio*; do	
		IDENTIFIER=${DEVICE:10}
		echo $PROGRAM $DEVICE $BAUDRATE $IDENTIFIER
		$PROGRAM $DEVICE $BAUDRATE $IDENTIFIER &
	done
	jobs
	wait
)
