#!/bin/bash
# $Id: perdevice,v 1.2 2009-03-25 07:07:47 nick Exp $

PROGRAM=$1
BAUDRATE=${2:-9600}

./identify.pl | (
    while read DEVICE IDENTIFIER ETC; do
        $PROGRAM $DEVICE $BAUDRATE $IDENTIFIER &
    done
    wait
)
