#!/bin/bash
# $Id: perdevsort,v 1.2 2009-08-05 06:18:30 nick Exp $

PROGRAM=$1
BAUDRATE=${2:-9600}
TEMPMASTER=`tempfile`
OUTFILE=`date +run.%Y%m%d_%H%M%S.dat`
echo "GENERATING $OUTFILE" > /dev/stderr

(
    for DEVICE in /dev/radio*; do
	IDENTIFIER=${DEVICE:10}
        TEMPFILE=`tempfile`
        echo $TEMPFILE
        echo $PROGRAM $DEVICE $BAUDRATE $IDENTIFIER \> $TEMPFILE > /dev/stderr
        $PROGRAM $DEVICE $BAUDRATE $IDENTIFIER > $TEMPFILE &
    done
    wait
) > $TEMPMASTER

cat $TEMPMASTER | xargs cat | sort -n > $OUTFILE
echo "GENERATED $OUTFILE" > /dev/stderr

cat $TEMPMASTER | xargs rm
rm $TEMPMASTER
