#!/usr/bin/env python
# $Id: symbols.py,v 1.2 2009-01-14 07:52:12 nick Exp $
import random
import re
import sys

print "/* Autogenerated by `%s` ... do not edit */" % ' '.join(sys.argv)

# Note that 0 = MARK, 1 = SPACE
# Note that START = SPACE, END = MARK

maxones  = int(sys.argv[1]) if len(sys.argv) > 1 else 3
minones  = int(sys.argv[2]) if len(sys.argv) > 2 else 1
maxzeros = int(sys.argv[3]) if len(sys.argv) > 3 else maxones
minzeros = int(sys.argv[4]) if len(sys.argv) > 4 else minones

sre = re.compile("^(1{%d,%d}0{%d,%d})+$" % (minones,maxones,minzeros,maxzeros))

symbols = []
for symbol in range(0, 256):
    x = '1'
    for bit in [1,2,4,8,16,32,64,128]:
        x += (symbol & bit) and '0' or '1'
    x += '0'
    if sre.match(x):
        symbols.append(chr(symbol))
        
print

print "#define NSYMBOLS (%d)" % len(symbols)

print

print "unsigned char encode[NSYMBOLS] = {",
for n, s in enumerate(symbols):
    if not n % 8: print "\n\t",
    print "0x%02X," % ord(s),
print "\n};"

decode = [ -1 ] * 256;
for n, s in enumerate(symbols):
    decode[ord(s)] = n;
    
print

print "int decode[256] = {",
for n, d in enumerate(decode):
    if not (n % 8): print "\n\t",
    print "%3d," % d,
print "\n};"